# Generated by Django 4.1.2 on 2022-10-24 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_artist_nb_album"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artist",
                to="app.artist",
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="genre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="genres",
                to="app.genre",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="app.album",
            ),
        ),
    ]
