# Generated by Django 4.1.2 on 2022-10-28 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_track_artist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="artist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artists",
                to="app.artist",
            ),
        ),
    ]
